controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

gitlab_webhook:
    path: /webhook/gitlab
    controller: App\Controller\WebhookController::handleWebhook
    methods: [POST]
